config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :homes, only:  [:index]
  resources :posts do
    resources :comments
    resources :favourites, only: [:create, :destroy]
  end

  resources :favourites, only: [:index]

  get "/abouts" => "abouts#index"


  root "homes#index"

end

app/models/categorization.rb
class Categorization < ActiveRecord::Base
  belongs_to :post
  belongs_to :category
end

app/models/category.rb
class Category < ActiveRecord::Base
  validates :title, presence: true

  has_many :categorizations, dependent: :destroy
  has_many :posts, through: :categorizations
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  validates :body, presence: true,
                   uniqueness: {scope: :post_id}

  belongs_to :post
  belongs_to :user

  scope :recent, lambda { order("created_at DESC") }

end

app/models/contact.rb
class Contact < ActiveRecord::Base
end

app/models/favourite.rb
class Favourite < ActiveRecord::Base
  belongs_to :user
  belongs_to :post

    validates :user_id, uniqueness: {scope: :post_id}
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/models/post.rb
class Post < ActiveRecord::Base
  validates :title, presence: true,
                    uniqueness: {case_sensitive: false}

  has_many :comments, dependent: :destroy
  has_many :favourites, dependent: :destroy
  has_many :favourited_users, through: :favourites, source: :user
  has_many :categorizations, dependent: :destroy
  has_many :categories, through: :categorizations

  belongs_to :user

  def favourite_for(user)
    favourites.find_by_user_id(user.id) if user
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :posts, dependent: :nullify
  has_many :comments, dependent: :nullify
  has_many :favourites, dependent: :destroy
  has_many :favourited_posts, through: :favourites, source: :post
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def name_display
    if first_name || last_name
      "#{first_name} #{last_name}".strip.squeeze(" ")
    else
      email
    end
  end
end

app/controllers/abouts_controller.rb
class AboutsController < ApplicationController

  def index
    
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_params, if: :devise_controller?
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
      request.env['omniauth.origin'] || stored_location_for(resource) || new_post_path
  end

  private
  
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) << [:first_name, :last_name]
    devise_parameter_sanitizer.for(:account_update) << [:first_name, :last_name]
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!
  
  def create
    @post = Post.find params[:post_id]
    @comment = Comment.new(comment_params)
    @comment.user = current_user
    @comment.post = @post

    if @comment.save
      redirect_to post_path(@post), notice: "Comment created"
    else
      render "posts/show"
    end
  end

  def edit
    @post = Post.find params[:post_id]
    @comment   = Comment.find params[:id]
  end

  def update
    @post = Post.find params[:post_id]
    @comment   = Comment.find params[:id]
    if @comment.update comment_params
      redirect_to @post, notice: "Comment updated"
    else
      render :edit
    end
  end

  def destroy
    @post = Post.find params[:post_id]
    @comment = Comment.find params[:id]
    @comment.destroy
    redirect_to post_path(@post), notice: "Comment deleted"
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/favourites_controller.rb
class FavouritesController < ApplicationController
  before_action :authenticate_user!

  def index
    @favourited_posts = current_user.favourited_posts
  end

  def create
    @post = Post.find params[:post_id]
    @favourite = current_user.favourites.new
    @favourite.post = @post
    if @favourite.save
      redirect_to @post, notice: "Favourited!"
    else
      redirect_to @post, alert: "Not favourited!"
    end
  end

  def destroy
    @favourite = current_user.favourites.find params[:id]
    @post = @favourite.post
    @favourite.destroy
    redirect_to @post, notice: "Unfavourited"
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def index
    render :layout => 'external'
  end

  def show
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:edit, :update, :destroy]

  def index
    @posts = Post.all
  end

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      flash[:notice] = "Blog post saved"
      redirect_to post_path(@post)
    else
      flash[:notice] = "You can't have empty fields"
      render :new
    end
  end

  def show
    @post = Post.find params[:id]
    @comment = Comment.new
    @favourite = @post.favourite_for(current_user) if user_signed_in?
  end

  def edit
  end

  def update
    if @post.update(post_params)
      flash[:notice] = "Blog post updated"
      redirect_to @post
    else
      flash[:notice] = "You can't have empty fields"
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path
  end

  private

  def find_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :body, {category_ids: []})
  end

end

app/helpers/abouts_helper.rb
module AboutsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favourites_helper.rb
module FavouritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/abouts/index.html.erb
<h2>About</h2>
<%= link_to image_tag(
  "https://pbs.twimg.com/profile_images/378800000182500573/27fc4f9ac9975a326288ab895d611c90_400x400.jpeg", 
  :size => "100x100") %>
<br>
This is a caffeinated blog.

app/views/comments/_comment.html.erb
<% comment.body %>
  <%= button_to "Delete", post_comment_path(@post, comment), method: :delete, data: {confirm: "Are you sure?"} %>
  <%= link_to "Edit", edit_post_comment_path(@post, comment) %>
<% end %>
<hr>

app/views/comments/_form.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.text_field :body, placeholder: "Put your comment here" %>
  <br>
  <%= f.submit "Submit Comment", class: "btn btn-primary" %> 
<% end %>

app/views/comments/edit.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.text_field :body %>
  <br>
  <%= f.submit "Submit Comment", class: "btn btn-primary" %> 
<% end %>

app/views/favourites/_favourite.html.erb
<p>Favourited: <%= @post.favourites.count %> times</p>

<% if @favourite.present? && @favourite.persisted? %>
  <%= link_to "Unfavourite", post_favourite_path(@post, @favourite), method: :delete %>
<% else %>
  <%= link_to "Favourite", post_favourites_path(@post), method: :post %>
<% end %>

app/views/favourites/index.html.erb
<h1>Favourited Blog Posts</h1>
<% @favourited_posts.each do |post| %>
  <%= link_to post.title, post %>
  <br>
<% end %>

app/views/homes/index.html.erb
<h2>Home</h2>
This is the homepage.

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coffee Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="header">
    <div style="float: right">
      <% if user_signed_in? %>
        Welcome <%= current_user.name_display %>,
        <%= link_to "Favourites", favourites_path %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Log In", new_user_session_path %>
        <%= link_to "Register", new_user_registration_path %>
      <% end %>
    </div>
    <h1>Coffee Blog</h1>
    <%= link_to "Home", homes_path %>
    |
    <%= link_to "Blog Posts", posts_path %>
    |
    <%= link_to "About", abouts_path %>
  </div>
  <div class="container">
    <%= flash[:notice] || flash[:alert] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/external.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Welcome to Coffee Blog</title>
  <%= stylesheet_link_tag    'external', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="external">
    <h1>Coffee Blog</h1>
    <div>
      <% if user_signed_in? %>
        Welcome <%= current_user.name_display %>
        <%= link_to "Log Out", destroy_user_session_path, method: :delete %>
      <% else %>
        <%= link_to "Log In", new_user_session_path %>
        <%= link_to "Register", new_user_registration_path %>
      <% end %>
    </div>
    <div>
    <%= link_to "Home", homes_path %>
    |
    <%= link_to "Blog Posts", posts_path %>
    |
    <%= link_to "About", abouts_path %>
    </div>
  </div>
  <div class="container">
    <%= flash[:notice] || flash[:alert] %>
    <%= yield %>
  </div>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :body %>
  <%= f.text_area :body %>
  <br>
  <%= f.collection_check_boxes :category_ids, Category.all, :id, :title %>
  <br>
  <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/posts/edit.html.erb
<h2>Edit Blog Post</h2>
<%= render "form" %>

app/views/posts/index.html.erb
<h2>Blog Posts</h2>
<%= link_to "New Blog Post", new_post_path, class: "btn btn-primary" %>
<br>
<br>
<% @posts.each do |post| %>
  <%= link_to post.title, post_path(post) %>
  <hr/>
<% end %>

app/views/posts/new.html.erb
<h2>Create New Blog Post</h2>
<%= render "form" %>

app/views/posts/show.html.erb
<h2><%= @post.title %></h2>
<% if @post.user.present? %>
  <p><em>Created By: <%= @post.user.name_display %></em></p>
<% end %>
<p><%= @post.body %></p>
<%= link_to "Edit", edit_post_path(@post), class: "btn btn-primary" %>
<%= link_to "Delete", post_path(@post), method: :delete, data: {confirm: "Are you sure?"},
  class: "btn btn-danger" %>
<div class="favourite">
  <%= render partial: "/favourites/favourite" %>
</div>
<hr>
<div class="comments">
<h3>Comments</h3>
<%= render partial: "/comments/form" %>
<br>
<% @post.comments.each do |comment| %>
  <%= comment.body %>
  <%= link_to "Edit Comment", edit_post_comment_path(@post, comment), class: "btn btn-primary" %>
  <%= link_to "Delete Comment", post_comment_path(@post, comment), method: :delete, 
    class: "btn btn-danger", data: {confirm: "Are you sure?"} %>
  <hr/>
<% end %>
</div>